### ISSUE TITLE
Starting Container takes a lot of time

### ISSUE THREAD

**Issue by yoletech** [linuxserver/docker-cloud9#17]
Hil all,

When starting the container in my windows 10 wsl2 system , I face this issue sayin Setting permissions  , but at each run it took a lot of time to startup , any solution to this ?

cloud9    | [cont-init.d] 10-adduser: exited 0.
cloud9    | [cont-init.d] 30-config: executing...
cloud9    | Cloning into '/code'...
cloud9    | [cont-init.d] Setting permissions this may take some time

**Comment by dexter74** [comment]
Hello,
Just wait 5 minutes & work perfect.

**Comment by thelamer** [comment]
It is a perms thing and part of having a dynamic user PUID/GUID. I Know and even splash the `[cont-init.d] Setting permissions this may take some time` message.
