### ISSUE TITLE
Outdated eslint

### ISSUE THREAD

**Issue by drmrbrewer** [linuxserver/docker-cloud9#22]
Nice image... I've been using a self-hosted Cloud9 IDE of my own for years, based off the [c9-core repo](https://github.com/c9/core).  It's served me well but more recently it's started to fall behind in terms of eslint, showing an error for something that isn't an error... as [reported here](https://stackoverflow.com/q/70009442/4070848).  I was hoping that this Cloud9 image from linuxserver would have been based on a modified version that has an updated linter, but it seems that it's probably just based on the original core c9, which is now 4 years old... I've tried myself to update the eslint stuff, but as explained in the SO post (and comments to the one answer) it's seemingly beyond my skill level.  It would be great if the geniuses at linuxserver could update the baked-in eslint to keep it up with the latest developments, because Cloud9 is still a very capable IDE otherwise.

**Comment by drizuid** [comment]
Please fill out the template
