### ISSUE TITLE
HTTP Auth

### ISSUE THREAD

**Issue by reavessm** [linuxserver/docker-cloud9#7]
# Feature Request

Http authentication

`Warning: running cloud9 without using HTTP authentication ... use -a username:password to setup HTTP authentication`

I don't want my IDE available to the whole world, but I do want it available to me, wherever I am in the world

**Comment by c21xdx** [comment]
me too

**Comment by aptalca** [comment]
We'll look into it, but in the meantime, we recommend setting http auth in your reverse proxy
